### ISSUE TITLE
Roadmap for the Week

### ISSUE THREAD

**Issue by gregorygo12** [stefanvasilev/egnn-transformer#7]
- [ ] _Get baseline results for the base EGNN and standard transformer_.
- [ ] _Implement positional encodings in the edge features_.
- [ ] _Add flag for if coordinates should be used by the EGNN._
- [ ] _Implement the node-feature only transformer._
